import { REGISTRY, ENTITY_TYPES, type EntityTypeKey } from "./registry";
import type { CollectedEntity, FieldValue } from "./collect";

// ---------------------------------------------------------------------------
// Turns collected entity records into the campaign.md text. Hand-rolled
// (rather than handing the whole record to js-yaml's dump()) so the output
// stays exactly as readable/editable as Aviv's own vault notes: short fields
// stay plain scalars, prose fields become `|` literal blocks, reference
// lists become plain YAML lists of names. Every per-entity block is still
// itself valid YAML underneath the formatting choices, so parse.ts can
// safely hand each block straight to js-yaml's load() rather than needing
// its own hand-rolled parser - only the "which lines belong to this entity"
// splitting is custom, not the value parsing.
//
// IMPORTANT: this module assumes "image" kind fields already hold a
// zip-relative path (e.g. "images/characters/julian-salvatore.png") or
// null/empty - NOT the original blob URL / local path from the database.
// Swapping the original source for the zip path is export.ts's job (it's
// the only module that needs to fetch bytes), which keeps this module a
// pure "records in, text out" transform, symmetric with parse.ts.
// ---------------------------------------------------------------------------

function looksLikeOtherType(s: string): boolean {
  return /^(true|false|null|yes|no|~|[-+]?\d+(\.\d+)?)$/i.test(s.trim());
}

function needsQuoting(s: string): boolean {
  if (s === "") return true;
  if (/^\s|\s$/.test(s)) return true;
  if (/^[-?:,[\]{}#&*!|>'"%@`]/.test(s)) return true;
  if (/: |:$/.test(s)) return true;
  if (/ #/.test(s)) return true;
  if (looksLikeOtherType(s)) return true;
  return false;
}

function scalar(value: string): string {
  return needsQuoting(value) ? JSON.stringify(value) : value;
}

function emitLine(key: string, value: FieldValue, kind: string): string {
  if (kind === "text") {
    const text = value == null ? "" : String(value);
    if (text.trim() === "") return `${key}: ""`;
    const lines = text.replace(/\s+$/, "").split("\n");
    return [`${key}: |`, ...lines.map((l) => `  ${l}`)].join("\n");
  }
  if (kind === "refList") {
    const list = (Array.isArray(value) ? value : []) as string[];
    if (list.length === 0) return `${key}: []`;
    return [`${key}:`, ...list.map((v) => `  - ${scalar(v)}`)].join("\n");
  }
  if (kind === "boolean") {
    return `${key}: ${value ? "true" : "false"}`;
  }
  if (kind === "number") {
    return `${key}: ${value == null ? 0 : value}`;
  }
  // string, image, ref - all plain/quoted scalars, or empty.
  const s = value == null ? "" : String(value);
  return `${key}: ${scalar(s)}`;
}

function serializeEntity(type: EntityTypeKey, entity: CollectedEntity): string {
  const schema = REGISTRY[type];
  const lines: string[] = [`## ${entity.identity || "(untitled)"}`];
  for (const field of schema.fields) {
    lines.push(emitLine(field.key, entity.record[field.key] ?? null, field.kind));
  }
  return lines.join("\n");
}

/** Full campaign.md body for one collected snapshot. Empty types are omitted entirely rather than emitted as an empty <Tag></Tag>. */
export function serializeCampaign(collected: Record<EntityTypeKey, CollectedEntity[]>): string {
  const parts: string[] = [
    "<!--",
    "  Erendyl Codex campaign export.",
    "  Generated by the Codex admin panel's Campaign Export feature.",
    "  Each <Tag>...</Tag> block holds one entity type; each ## heading inside",
    "  it is one entity, followed by a YAML field block. Hand-editing is fine -",
    "  keep the tag names and field keys as-is so re-import can parse it.",
    "-->",
    "",
  ];
  for (const type of ENTITY_TYPES) {
    const entities = collected[type];
    if (!entities || entities.length === 0) continue;
    const schema = REGISTRY[type];
    parts.push(`<${schema.tag}>`, "");
    for (const entity of entities) {
      parts.push(serializeEntity(type, entity), "");
    }
    parts.push(`</${schema.tag}>`, "");
  }
  return parts.join("\n").replace(/\n{3,}/g, "\n\n").trim() + "\n";
}
